[tool.poetry]
name = "az-prod"
version = "0.1.0"
description = "Sistema de Gestión de Pedidos AZ"
authors = ["cesarlinares1522@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^5.0"
gunicorn = "^21.2.0"
psycopg2-binary = "^2.9.9"  # Si usas PostgreSQL
whitenoise = "^6.6.0"  # Para archivos estáticos

[tool.poetry.group.dev.dependencies]
debugpy = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"