# Generated by Django 5.2.1 on 2025-05-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('diseño_url', models.URLField()),
                ('estado', models.CharField(choices=[('diseno', 'Diseño Listo'), ('impresion', 'En Impresión'), ('entelado', 'En Entelado'), ('embolsado', 'En Embolsado'), ('finalizado', 'Finalizado')], default='diseno', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
